version: '3.7'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  app:
    build: .
    restart: always
    ports: 
      - 8081:8081
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: test
      DB_PASSWORD: test
      API_PORT: 8081

networks:
  internal:
