[functions]
    directory = "netlify/functions/"

[dev]
    command = "yarn start:app"
    publish = "dist"
    targetPort = 8080
    port = 1234
    framework = "vite"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
