[functions]
    directory = "netlify/functions/"

[dev]
    command = "yarn start:parcel"
    publish = "dist"
    targetPort = 8080
    port = 1234
    framework = "parcel"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
