[functions]
    directory = "netlify/functions/"

[dev]
    command = "yarn start:parcel"
    publish = "packages/app/dist"
    targetPort = 1234
    port = 8080
    framework = "parcel"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
